name: Print Issue Number and Context

on:
  issues:
    types: [opened, edited]
    
jobs:
  add-issue-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Issue Number
        run: echo '${{ github.event.issue.number }}'
        shell: bash

      - name: "GitHub Context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
