name: Create new command in new issues 

on:
  issues:
    types: [opened, edited]
    
jobs:
  add-issue-command:
    runs-on: ubuntu-latest
    steps:
      - name: "github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

    
