name: Create new command in new issues 

on:
  issues:
    types:  [opened, edited]
    
jobs:
  add-issue-command:
    runs-on: ubuntu-latest
    steps:
    - name: "github context"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
       
    - name: Add assigness
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'add-assignees'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        assignees: 'xxx'
        random-to: 1
    
    
